batch_size = 512
blocks = ['LSTM', 'linear', 'MLP']
loss_function = 'MSE'
regularization = False
target_lookahead = 2
epochs = 100
features = (0, 1, 2, 3)
normalize_data = True
hidden_parameters = 15
hidden_layers = 1
dropout = 0.5